name: "Install dependencies"
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update -q
        sudo apt-get install -y \
          libtesseract-dev libleptonica-dev \
          xorg-dev libxcb-composite0-dev libxcb-cursor-dev \
          libdbus-1-dev pkg-config
      shell: bash
